/**
 * =====================================================================
 * DATASET SÂN CẦU LÔNG – MÔ PHỎNG DỮ LIỆU THỰC TẾ
 * =====================================================================
 *
 * NGUỒN DỮ LIỆU:
 *   - Tên sân, địa chỉ, quận: tham khảo từ nền tảng ALO Booking và các
 *     nguồn công khai khác (Google Maps, bài viết, ...).
 *   - Các trường số (giá, khoảng cách, đánh giá, chất lượng, tiện ích,
 *     khung giờ, khả năng đáp ứng) được mô phỏng dựa trên kinh nghiệm
 *     thực tế và dữ liệu thống kê, nhằm phục vụ mục đích học tập.
 *
 * MỤC ĐÍCH:
 *   - Cung cấp dữ liệu đầu vào cho hệ thống hỗ trợ ra quyết định (AHP + TOPSIS)
 *   - Đảm bảo tính đa dạng, phong phú và sát với thực tế để minh họa
 *     bài toán lựa chọn sân cầu lông.
 *
 * CẤU TRÚC MỖI SÂN:
 *   - id          : Mã sân (duy nhất)
 *   - name        : Tên sân
 *   - address     : Địa chỉ chi tiết
 *   - district    : Quận / khu vực
 *   - price       : Giá thuê (VNĐ/giờ) – tiêu chí COST
 *   - distance    : Khoảng cách từ trung tâm (km) – tiêu chí COST
 *   - rating      : Đánh giá trung bình (thang 1–5) – tiêu chí BENEFIT
 *   - quality     : Chất lượng mặt sân, thiết bị (thang 1–10) – BENEFIT
 *   - facilities  : Số tiện ích đi kèm – BENEFIT
 *   - facilityList: Mảng các tiện ích cụ thể (để hiển thị)
 *   - openFrom    : Giờ mở cửa (giờ, 24h)
 *   - openTo      : Giờ đóng cửa (giờ, 24h)
 *   - availability: Khả năng đáp ứng khung giờ (0–1, 1 = còn nhiều sân trống) – BENEFIT
 *   - url         : Đường dẫn tham khảo trên ALO Booking (mô phỏng)
 *
 * =====================================================================
 */

const COURTS = [
  // -------------------- Khu vực Gò Vấp --------------------
  {
    id: "C001",
    name: "Sân cầu lông Hải Đăng",
    address: "12 Nguyễn Văn Bảo, P.4, Gò Vấp",
    district: "Gò Vấp",
    price: 90000,
    distance: 3.2,
    rating: 4.6,
    quality: 9.0,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 6,
    openTo: 22,
    availability: 0.8,
    url: "https://alobooking.vn/san/hai-dang"
  },
  {
    id: "C002",
    name: "Sân cầu lông Phương Nam",
    address: "90 Quang Trung, Gò Vấp",
    district: "Gò Vấp",
    price: 65000,
    distance: 2.5,
    rating: 3.9,
    quality: 6.5,
    facilities: 2,
    facilityList: ["Gửi xe", "Phòng thay đồ"],
    openFrom: 6,
    openTo: 21,
    availability: 0.95,
    url: "https://alobooking.vn/san/phuong-nam"
  },
  {
    id: "C003",
    name: "Sân cầu lông Victory",
    address: "102 Nguyễn Oanh, Gò Vấp",
    district: "Gò Vấp",
    price: 105000,
    distance: 3.8,
    rating: 4.7,
    quality: 9.2,
    facilities: 6,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi", "Cho thuê vợt"],
    openFrom: 5,
    openTo: 23,
    availability: 0.72,
    url: "https://alobooking.vn/san/victory"
  },
  {
    id: "C004",
    name: "Sân cầu lông Ánh Sao",
    address: "67 Lê Đức Thọ, Gò Vấp",
    district: "Gò Vấp",
    price: 92000,
    distance: 3.0,
    rating: 4.5,
    quality: 8.4,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 5,
    openTo: 23,
    availability: 0.7,
    url: "https://alobooking.vn/san/anh-sao"
  },
  {
    id: "C005",
    name: "Sân cầu lông Lộc Phát",
    address: "150 Phan Huy Ích, Gò Vấp",
    district: "Gò Vấp",
    price: 62000,
    distance: 4.9,
    rating: 3.9,
    quality: 6.6,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 6,
    openTo: 22,
    availability: 0.9,
    url: "https://alobooking.vn/san/loc-phat"
  },
  {
    id: "C006",
    name: "CLB cầu lông Phương Đông",
    address: "181 Phan Văn Trị, Gò Vấp",
    district: "Gò Vấp",
    price: 105000,
    distance: 5.4,
    rating: 4.3,
    quality: 8.7,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 5,
    openTo: 24,
    availability: 0.82,
    url: "https://alobooking.vn/san/clb-cau-long-phuong-dong-100"
  },

  // -------------------- Khu vực Bình Thạnh --------------------
  {
    id: "C007",
    name: "Sân cầu lông Thành Công",
    address: "45 Phan Văn Trị, Bình Thạnh",
    district: "Bình Thạnh",
    price: 70000,
    distance: 5.0,
    rating: 4.2,
    quality: 7.5,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 6,
    openTo: 23,
    availability: 0.9,
    url: "https://alobooking.vn/san/thanh-cong"
  },
  {
    id: "C008",
    name: "Sân cầu lông Sài Gòn",
    address: "56 Điện Biên Phủ, Bình Thạnh",
    district: "Bình Thạnh",
    price: 100000,
    distance: 5.5,
    rating: 4.5,
    quality: 8.6,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 6,
    openTo: 23,
    availability: 0.65,
    url: "https://alobooking.vn/san/sai-gon"
  },
  {
    id: "C009",
    name: "Sân cầu lông Sông Xanh",
    address: "45 Xô Viết Nghệ Tĩnh, Bình Thạnh",
    district: "Bình Thạnh",
    price: 88000,
    distance: 5.3,
    rating: 4.3,
    quality: 8.0,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "WiFi"],
    openFrom: 5,
    openTo: 22,
    availability: 0.78,
    url: "https://alobooking.vn/san/song-xanh"
  },
  {
    id: "C010",
    name: "CLB cầu lông Tân Sơn",
    address: "108 Nguyễn Hữu Thọ, Bình Thạnh",
    district: "Bình Thạnh",
    price: 85000,
    distance: 6.8,
    rating: 4.0,
    quality: 6.9,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 5,
    openTo: 22,
    availability: 0.59,
    url: "https://alobooking.vn/san/clb-cau-long-tan-son-78"
  },

  // -------------------- Khu vực Quận 1 --------------------
  {
    id: "C011",
    name: "Sân cầu lông Bình Minh",
    address: "5 Nguyễn Thị Minh Khai, Quận 1",
    district: "Quận 1",
    price: 150000,
    distance: 9.8,
    rating: 4.9,
    quality: 9.8,
    facilities: 6,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi", "Cho thuê vợt"],
    openFrom: 6,
    openTo: 24,
    availability: 0.5,
    url: "https://alobooking.vn/san/binh-minh"
  },
  {
    id: "C012",
    name: "CLB cầu lông Phú Thịnh",
    address: "109 Bến Vân Đồn, Quận 1",
    district: "Quận 1",
    price: 105000,
    distance: 9.7,
    rating: 4.3,
    quality: 8.6,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 6,
    openTo: 22,
    availability: 0.87,
    url: "https://alobooking.vn/san/clb-cau-long-phu-thinh-40"
  },
  {
    id: "C013",
    name: "Sân cầu lông Tây Đô",
    address: "194 Cộng Hòa, Quận 1",
    district: "Quận 1",
    price: 60000,
    distance: 4.1,
    rating: 3.6,
    quality: 5.7,
    facilities: 2,
    facilityList: ["Gửi xe", "Căng tin"],
    openFrom: 5,
    openTo: 22,
    availability: 0.82,
    url: "https://alobooking.vn/san/san-cau-long-tay-do-49"
  },

  // -------------------- Khu vực TP. Thủ Đức --------------------
  {
    id: "C014",
    name: "Sân cầu lông Ngôi Sao",
    address: "78 Lê Văn Việt, TP. Thủ Đức",
    district: "TP. Thủ Đức",
    price: 120000,
    distance: 8.5,
    rating: 4.8,
    quality: 9.5,
    facilities: 6,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi", "Cho thuê vợt"],
    openFrom: 5,
    openTo: 23,
    availability: 0.6,
    url: "https://alobooking.vn/san/ngoi-sao"
  },
  {
    id: "C015",
    name: "Sân cầu lông Ánh Dương",
    address: "8 Phạm Văn Đồng, TP. Thủ Đức",
    district: "TP. Thủ Đức",
    price: 95000,
    distance: 6.0,
    rating: 4.1,
    quality: 7.8,
    facilities: 3,
    facilityList: ["Gửi xe", "Máy lạnh", "WiFi"],
    openFrom: 5,
    openTo: 23,
    availability: 0.8,
    url: "https://alobooking.vn/san/anh-duong"
  },
  {
    id: "C016",
    name: "Sân cầu lông Đông Đô",
    address: "3 Kha Vạn Cân, TP. Thủ Đức",
    district: "TP. Thủ Đức",
    price: 80000,
    distance: 6.4,
    rating: 4.2,
    quality: 7.6,
    facilities: 3,
    facilityList: ["Gửi xe", "Máy lạnh", "WiFi"],
    openFrom: 6,
    openTo: 22,
    availability: 0.8,
    url: "https://alobooking.vn/san/dong-do"
  },
  {
    id: "C017",
    name: "Sân cầu lông Center Court",
    address: "8 Mai Chí Thọ, TP. Thủ Đức",
    district: "TP. Thủ Đức",
    price: 130000,
    distance: 7.1,
    rating: 4.7,
    quality: 9.1,
    facilities: 6,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi", "Cho thuê vợt"],
    openFrom: 5,
    openTo: 24,
    availability: 0.6,
    url: "https://alobooking.vn/san/center-court"
  },

  // -------------------- Khu vực Tân Bình --------------------
  {
    id: "C018",
    name: "Sân cầu lông Á Châu",
    address: "34 Trường Chinh, Tân Bình",
    district: "Tân Bình",
    price: 85000,
    distance: 4.1,
    rating: 4.4,
    quality: 8.2,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "WiFi"],
    openFrom: 5,
    openTo: 22,
    availability: 0.75,
    url: "https://alobooking.vn/san/a-chau"
  },
  {
    id: "C019",
    name: "Sân cầu lông Bình Dân",
    address: "88 Âu Cơ, Tân Bình",
    district: "Tân Bình",
    price: 58000,
    distance: 4.6,
    rating: 3.8,
    quality: 6.2,
    facilities: 2,
    facilityList: ["Gửi xe", "Căng tin"],
    openFrom: 6,
    openTo: 21,
    availability: 0.92,
    url: "https://alobooking.vn/san/binh-dan"
  },
  {
    id: "C020",
    name: "Sân cầu lông Đại Việt",
    address: "21 Cộng Hòa, Tân Bình",
    district: "Tân Bình",
    price: 115000,
    distance: 5.9,
    rating: 4.6,
    quality: 8.8,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 5,
    openTo: 23,
    availability: 0.66,
    url: "https://alobooking.vn/san/dai-viet"
  },
  {
    id: "C021",
    name: "Sân cầu lông Tân Thành",
    address: "64 Điện Biên Phủ, Tân Bình",
    district: "Tân Bình",
    price: 65000,
    distance: 3.8,
    rating: 3.9,
    quality: 6.7,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 5,
    openTo: 24,
    availability: 0.87,
    url: "https://alobooking.vn/san/san-cau-long-tan-thanh-38"
  },

  // -------------------- Khu vực Tân Phú --------------------
  {
    id: "C022",
    name: "Sân cầu lông Tân Phú",
    address: "17 Lũy Bán Bích, Tân Phú",
    district: "Tân Phú",
    price: 60000,
    distance: 7.2,
    rating: 3.7,
    quality: 6.0,
    facilities: 2,
    facilityList: ["Gửi xe", "Căng tin"],
    openFrom: 6,
    openTo: 21,
    availability: 0.9,
    url: "https://alobooking.vn/san/tan-phu"
  },
  {
    id: "C023",
    name: "Sân cầu lông Hương Việt",
    address: "34 Tân Kỳ Tân Quý, Tân Phú",
    district: "Tân Phú",
    price: 68000,
    distance: 6.8,
    rating: 4.0,
    quality: 6.9,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "WiFi"],
    openFrom: 6,
    openTo: 22,
    availability: 0.88,
    url: "https://alobooking.vn/san/huong-viet"
  },
  {
    id: "C024",
    name: "Nhà thi đấu Trường Sơn",
    address: "24 Phạm Văn Đồng, Tân Phú",
    district: "Tân Phú",
    price: 115000,
    distance: 8.3,
    rating: 4.3,
    quality: 8.8,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 5,
    openTo: 23,
    availability: 0.84,
    url: "https://alobooking.vn/san/nha-thi-dau-truong-son-28"
  },

  // -------------------- Khu vực Quận 3 --------------------
  {
    id: "C025",
    name: "Sân cầu lông Đại Dương",
    address: "23 Cách Mạng Tháng 8, Quận 3",
    district: "Quận 3",
    price: 110000,
    distance: 6.7,
    rating: 4.3,
    quality: 8.0,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Máy lạnh", "WiFi"],
    openFrom: 6,
    openTo: 22,
    availability: 0.7,
    url: "https://alobooking.vn/san/dai-duong"
  },
  {
    id: "C026",
    name: "Sân cầu lông Minh Khai",
    address: "72 Nguyễn Thị Minh Khai, Quận 3",
    district: "Quận 3",
    price: 98000,
    distance: 5.7,
    rating: 4.4,
    quality: 8.1,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh"],
    openFrom: 6,
    openTo: 23,
    availability: 0.74,
    url: "https://alobooking.vn/san/minh-khai"
  },
  {
    id: "C027",
    name: "Sân cầu lông Bảo Ngọc",
    address: "171 Nguyễn Hữu Thọ, Quận 3",
    district: "Quận 3",
    price: 120000,
    distance: 2.9,
    rating: 4.6,
    quality: 9.5,
    facilities: 6,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi", "Cho thuê vợt"],
    openFrom: 6,
    openTo: 22,
    availability: 0.8,
    url: "https://alobooking.vn/san/san-cau-long-bao-ngoc-35"
  },

  // -------------------- Khu vực Quận 7 --------------------
  {
    id: "C028",
    name: "Sân cầu lông Newtown",
    address: "9 Nguyễn Hữu Thọ, Quận 7",
    district: "Quận 7",
    price: 135000,
    distance: 7.8,
    rating: 4.8,
    quality: 9.4,
    facilities: 6,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi", "Cho thuê vợt"],
    openFrom: 5,
    openTo: 24,
    availability: 0.58,
    url: "https://alobooking.vn/san/newtown"
  },
  {
    id: "C029",
    name: "Sân cầu lông Phú Mỹ Hưng",
    address: "12 Nguyễn Văn Linh, Quận 7",
    district: "Quận 7",
    price: 145000,
    distance: 8.9,
    rating: 4.9,
    quality: 9.7,
    facilities: 6,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi", "Cho thuê vợt"],
    openFrom: 6,
    openTo: 23,
    availability: 0.5,
    url: "https://alobooking.vn/san/phu-my-hung"
  },
  {
    id: "C030",
    name: "Sân cầu lông Quốc Tế",
    address: "129 Nguyễn Văn Linh, Quận 7",
    district: "Quận 7",
    price: 125000,
    distance: 7.2,
    rating: 4.4,
    quality: 9.2,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 5,
    openTo: 24,
    availability: 0.63,
    url: "https://alobooking.vn/san/san-cau-long-quoc-te-27"
  },
  {
    id: "C031",
    name: "Sân cầu lông Hưng Thịnh",
    address: "134 Quang Trung, Quận 7",
    district: "Quận 7",
    price: 105000,
    distance: 3.4,
    rating: 4.3,
    quality: 7.8,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh"],
    openFrom: 5,
    openTo: 22,
    availability: 0.63,
    url: "https://alobooking.vn/san/san-cau-long-hung-thinh-29"
  },

  // -------------------- Khu vực Quận 4 --------------------
  {
    id: "C032",
    name: "Sân cầu lông Riverside",
    address: "19 Bến Vân Đồn, Quận 4",
    district: "Quận 4",
    price: 125000,
    distance: 6.2,
    rating: 4.6,
    quality: 8.9,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 6,
    openTo: 23,
    availability: 0.64,
    url: "https://alobooking.vn/san/riverside"
  },
  {
    id: "C033",
    name: "Nhà thi đấu Đại Phát",
    address: "129 Quang Trung, Quận 4",
    district: "Quận 4",
    price: 65000,
    distance: 7.8,
    rating: 3.4,
    quality: 5.9,
    facilities: 2,
    facilityList: ["Gửi xe", "Căng tin"],
    openFrom: 6,
    openTo: 23,
    availability: 0.57,
    url: "https://alobooking.vn/san/nha-thi-dau-dai-phat-30"
  },
  {
    id: "C034",
    name: "Sân cầu lông Hồng Phúc",
    address: "159 Nguyễn Văn Linh, Quận 4",
    district: "Quận 4",
    price: 60000,
    distance: 6.7,
    rating: 3.6,
    quality: 6.3,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 5,
    openTo: 22,
    availability: 0.54,
    url: "https://alobooking.vn/san/san-cau-long-hong-phuc-31"
  },

  // -------------------- Khu vực Quận 12 --------------------
  {
    id: "C035",
    name: "Sân cầu lông Hoàng Gia",
    address: "27 Nguyễn Ảnh Thủ, Quận 12",
    district: "Quận 12",
    price: 75000,
    distance: 9.0,
    rating: 4.0,
    quality: 7.0,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 6,
    openTo: 22,
    availability: 0.85,
    url: "https://alobooking.vn/san/hoang-gia"
  },
  {
    id: "C036",
    name: "Sân cầu lông Thiên Long",
    address: "56 Tô Ký, Quận 12",
    district: "Quận 12",
    price: 55000,
    distance: 10.5,
    rating: 3.6,
    quality: 5.8,
    facilities: 2,
    facilityList: ["Gửi xe", "Phòng thay đồ"],
    openFrom: 6,
    openTo: 21,
    availability: 0.95,
    url: "https://alobooking.vn/san/thien-long"
  },
  {
    id: "C037",
    name: "Nhà thi đấu Hồng Phúc",
    address: "190 Cách Mạng Tháng 8, Quận 12",
    district: "Quận 12",
    price: 135000,
    distance: 11.3,
    rating: 4.7,
    quality: 9.6,
    facilities: 6,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi", "Cho thuê vợt"],
    openFrom: 5,
    openTo: 23,
    availability: 0.88,
    url: "https://alobooking.vn/san/nha-thi-dau-hong-phuc-44"
  },

  // -------------------- Khu vực Hóc Môn --------------------
  {
    id: "C038",
    name: "Sân cầu lông & Pickleball Sunshine",
    address: "60/2 Quang Trung, Thị trấn Hóc Môn",
    district: "Hóc Môn",
    price: 120000,
    distance: 8.5,
    rating: 4.6,
    quality: 8.5,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "WiFi"],
    openFrom: 6,
    openTo: 22,
    availability: 0.7,
    url: "https://datlich.alobo.vn/san/sport_sunshine"
  },
  {
    id: "C039",
    name: "Sân cầu lông Hồng Phát",
    address: "60/2 Quang Trung, Hóc Môn",
    district: "Hóc Môn",
    price: 95000,
    distance: 9.2,
    rating: 4.1,
    quality: 7.8,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "WiFi"],
    openFrom: 6,
    openTo: 22,
    availability: 0.76,
    url: "https://alobooking.vn/san/hong-phat"
  },

  // -------------------- Khu vực Bình Tân --------------------
  {
    id: "C040",
    name: "Sân cầu lông HAAN Badminton",
    address: "31A đường số 4, P. Bình Hưng Hòa A, Bình Tân",
    district: "Bình Tân",
    price: 90000,
    distance: 6.2,
    rating: 4.3,
    quality: 7.8,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 6,
    openTo: 23,
    availability: 0.85,
    url: "https://datlich.alobo.vn/san/ha-badminton"
  },
  {
    id: "C041",
    name: "Sân cầu lông Quang Huy",
    address: "110/2 Miếu Gò Xoài, Bình Hưng Hòa A, Bình Tân",
    district: "Bình Tân",
    price: 70000,
    distance: 7.0,
    rating: 3.9,
    quality: 6.8,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 6,
    openTo: 22,
    availability: 0.82,
    url: "https://alobooking.vn/san/quang-huy"
  },

  // -------------------- Các khu vực khác (mở rộng) --------------------
  {
    id: "C042",
    name: "Sân cầu lông Sao Mai",
    address: "109 Âu Cơ, Bình Tân",
    district: "Bình Tân",
    price: 70000,
    distance: 10.8,
    rating: 4.1,
    quality: 7.0,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 6,
    openTo: 24,
    availability: 0.61,
    url: "https://alobooking.vn/san/san-cau-long-sao-mai-26"
  },
  {
    id: "C043",
    name: "CLB cầu lông Đông Sài Gòn",
    address: "88 Quang Trung, Bình Tân",
    district: "Bình Tân",
    price: 55000,
    distance: 8.7,
    rating: 3.6,
    quality: 5.6,
    facilities: 2,
    facilityList: ["Gửi xe", "Căng tin"],
    openFrom: 5,
    openTo: 22,
    availability: 0.79,
    url: "https://alobooking.vn/san/clb-cau-long-dong-sai-gon-39"
  },
  {
    id: "C044",
    name: "Nhà thi đấu Ánh Nắng",
    address: "99 Cộng Hòa, Bình Tân",
    district: "Bình Tân",
    price: 75000,
    distance: 4.6,
    rating: 3.6,
    quality: 6.3,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 5,
    openTo: 22,
    availability: 0.58,
    url: "https://alobooking.vn/san/nha-thi-dau-anh-nang-75"
  },
  {
    id: "C045",
    name: "Sân cầu lông Hoàng Long",
    address: "13 Phạm Văn Đồng, Quận 10",
    district: "Quận 10",
    price: 85000,
    distance: 12.0,
    rating: 4.0,
    quality: 7.4,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh"],
    openFrom: 6,
    openTo: 22,
    availability: 0.69,
    url: "https://alobooking.vn/san/san-cau-long-hoang-long-76"
  },
  {
    id: "C046",
    name: "CLB cầu lông Tân Thành",
    address: "75 Kha Vạn Cân, Quận 3",
    district: "Quận 3",
    price: 80000,
    distance: 11.5,
    rating: 4.1,
    quality: 7.0,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 6,
    openTo: 23,
    availability: 0.62,
    url: "https://alobooking.vn/san/clb-cau-long-tan-thanh-77"
  },
  {
    id: "C047",
    name: "CLB cầu lông Bảo Ngọc",
    address: "14 Âu Cơ, Tân Bình",
    district: "Tân Bình",
    price: 55000,
    distance: 12.8,
    rating: 3.4,
    quality: 5.8,
    facilities: 2,
    facilityList: ["Gửi xe", "Căng tin"],
    openFrom: 5,
    openTo: 23,
    availability: 0.87,
    url: "https://alobooking.vn/san/clb-cau-long-bao-ngoc-79"
  },
  {
    id: "C048",
    name: "Sân cầu lông Thiên Phú",
    address: "58 Nguyễn Văn Linh, Quận 7",
    district: "Quận 7",
    price: 65000,
    distance: 9.9,
    rating: 3.7,
    quality: 6.3,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 5,
    openTo: 21,
    availability: 0.71,
    url: "https://alobooking.vn/san/san-cau-long-thien-phu-80"
  },
  {
    id: "C049",
    name: "CLB cầu lông Kim Long",
    address: "67 Phạm Văn Đồng, Bình Tân",
    district: "Bình Tân",
    price: 60000,
    distance: 2.3,
    rating: 3.5,
    quality: 5.7,
    facilities: 2,
    facilityList: ["Gửi xe", "Căng tin"],
    openFrom: 5,
    openTo: 24,
    availability: 0.74,
    url: "https://alobooking.vn/san/clb-cau-long-kim-long-81"
  },
  {
    id: "C050",
    name: "CLB cầu lông Hoàng Long",
    address: "148 Trường Chinh, Quận 1",
    district: "Quận 1",
    price: 100000,
    distance: 7.6,
    rating: 4.0,
    quality: 7.7,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh"],
    openFrom: 5,
    openTo: 23,
    availability: 0.53,
    url: "https://alobooking.vn/san/clb-cau-long-hoang-long-82"
  },
  {
    id: "C051",
    name: "CLB cầu lông Hoàng Kim",
    address: "144 Quang Trung, Phú Nhuận",
    district: "Phú Nhuận",
    price: 75000,
    distance: 1.7,
    rating: 4.0,
    quality: 6.6,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 5,
    openTo: 24,
    availability: 0.93,
    url: "https://alobooking.vn/san/clb-cau-long-hoang-kim-83"
  },
  {
    id: "C052",
    name: "Nhà thi đấu Phúc Long",
    address: "61 Nguyễn Văn Linh, Tân Phú",
    district: "Tân Phú",
    price: 135000,
    distance: 7.4,
    rating: 4.8,
    quality: 9.5,
    facilities: 6,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi", "Cho thuê vợt"],
    openFrom: 5,
    openTo: 24,
    availability: 0.88,
    url: "https://alobooking.vn/san/nha-thi-dau-phuc-long-84"
  },
  {
    id: "C053",
    name: "Nhà thi đấu An Bình",
    address: "141 Lũy Bán Bích, Quận 12",
    district: "Quận 12",
    price: 125000,
    distance: 7.0,
    rating: 4.7,
    quality: 9.3,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 5,
    openTo: 24,
    availability: 0.93,
    url: "https://alobooking.vn/san/nha-thi-dau-an-binh-85"
  },
  {
    id: "C054",
    name: "Nhà thi đấu Tân Bình Phú",
    address: "61 Tô Ký, Quận 3",
    district: "Quận 3",
    price: 95000,
    distance: 10.3,
    rating: 4.1,
    quality: 7.7,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh"],
    openFrom: 6,
    openTo: 24,
    availability: 0.72,
    url: "https://alobooking.vn/san/nha-thi-dau-tan-binh-phu-86"
  },
  {
    id: "C055",
    name: "Nhà thi đấu Nam Long",
    address: "198 Kha Vạn Cân, Phú Nhuận",
    district: "Phú Nhuận",
    price: 95000,
    distance: 10.8,
    rating: 4.2,
    quality: 8.0,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh"],
    openFrom: 5,
    openTo: 22,
    availability: 0.83,
    url: "https://alobooking.vn/san/nha-thi-dau-nam-long-87"
  },
  {
    id: "C056",
    name: "CLB cầu lông Sao Mai",
    address: "77 Cách Mạng Tháng 8, Quận 3",
    district: "Quận 3",
    price: 55000,
    distance: 10.9,
    rating: 3.7,
    quality: 5.7,
    facilities: 2,
    facilityList: ["Gửi xe", "Căng tin"],
    openFrom: 6,
    openTo: 22,
    availability: 0.74,
    url: "https://alobooking.vn/san/clb-cau-long-sao-mai-88"
  },
  {
    id: "C057",
    name: "Sân cầu lông Kỳ Đồng",
    address: "15 Nguyễn Văn Linh, Quận 1",
    district: "Quận 1",
    price: 60000,
    distance: 10.4,
    rating: 3.7,
    quality: 6.0,
    facilities: 2,
    facilityList: ["Gửi xe", "Căng tin"],
    openFrom: 5,
    openTo: 22,
    availability: 0.58,
    url: "https://alobooking.vn/san/san-cau-long-ky-dong-89"
  },
  {
    id: "C058",
    name: "Nhà thi đấu Bến Thành",
    address: "168 Kha Vạn Cân, Tân Bình",
    district: "Tân Bình",
    price: 70000,
    distance: 10.7,
    rating: 4.0,
    quality: 6.7,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 5,
    openTo: 22,
    availability: 0.52,
    url: "https://alobooking.vn/san/nha-thi-dau-ben-thanh-90"
  },
  {
    id: "C059",
    name: "Sân cầu lông Cửu Long",
    address: "74 Âu Cơ, Quận 10",
    district: "Quận 10",
    price: 55000,
    distance: 6.3,
    rating: 3.6,
    quality: 6.2,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 5,
    openTo: 23,
    availability: 0.55,
    url: "https://alobooking.vn/san/san-cau-long-cuu-long-91"
  },
  {
    id: "C060",
    name: "Nhà thi đấu Tân Sơn",
    address: "167 Lũy Bán Bích, Tân Bình",
    district: "Tân Bình",
    price: 65000,
    distance: 2.0,
    rating: 3.6,
    quality: 6.0,
    facilities: 2,
    facilityList: ["Gửi xe", "Căng tin"],
    openFrom: 5,
    openTo: 23,
    availability: 0.64,
    url: "https://alobooking.vn/san/nha-thi-dau-tan-son-92"
  },
  {
    id: "C061",
    name: "Nhà thi đấu Hồng Hà",
    address: "75 Lũy Bán Bích, Bình Tân",
    district: "Bình Tân",
    price: 80000,
    distance: 4.3,
    rating: 4.1,
    quality: 7.4,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh"],
    openFrom: 5,
    openTo: 23,
    availability: 0.67,
    url: "https://alobooking.vn/san/nha-thi-dau-hong-ha-93"
  },
  {
    id: "C062",
    name: "Sân cầu lông Hồng Hà",
    address: "96 Quang Trung, Quận 4",
    district: "Quận 4",
    price: 95000,
    distance: 7.8,
    rating: 4.1,
    quality: 7.6,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh"],
    openFrom: 5,
    openTo: 23,
    availability: 0.66,
    url: "https://alobooking.vn/san/san-cau-long-hong-ha-94"
  },
  {
    id: "C063",
    name: "Sân cầu lông An Bình",
    address: "102 Phạm Văn Đồng, Bình Thạnh",
    district: "Bình Thạnh",
    price: 125000,
    distance: 7.5,
    rating: 4.6,
    quality: 8.9,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 5,
    openTo: 23,
    availability: 0.71,
    url: "https://alobooking.vn/san/san-cau-long-an-binh-95"
  },
  {
    id: "C064",
    name: "Nhà thi đấu Thủ Đô",
    address: "87 Bến Vân Đồn, TP. Thủ Đức",
    district: "TP. Thủ Đức",
    price: 100000,
    distance: 8.6,
    rating: 4.2,
    quality: 8.4,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 6,
    openTo: 21,
    availability: 0.67,
    url: "https://alobooking.vn/san/nha-thi-dau-thu-do-96"
  },
  {
    id: "C065",
    name: "Nhà thi đấu Nam Sài Gòn",
    address: "13 Kha Vạn Cân, Bình Tân",
    district: "Bình Tân",
    price: 115000,
    distance: 7.1,
    rating: 4.3,
    quality: 8.4,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 5,
    openTo: 23,
    availability: 0.94,
    url: "https://alobooking.vn/san/nha-thi-dau-nam-sai-gon-97"
  },
  {
    id: "C066",
    name: "Sân cầu lông Đại Thành",
    address: "23 Nguyễn Oanh, Quận 10",
    district: "Quận 10",
    price: 135000,
    distance: 5.8,
    rating: 4.7,
    quality: 9.3,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 6,
    openTo: 22,
    availability: 0.92,
    url: "https://alobooking.vn/san/san-cau-long-dai-thanh-98"
  },
  {
    id: "C067",
    name: "Nhà thi đấu Phú Nhuận",
    address: "129 Tô Ký, Tân Phú",
    district: "Tân Phú",
    price: 105000,
    distance: 2.1,
    rating: 4.5,
    quality: 8.8,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 5,
    openTo: 22,
    availability: 0.6,
    url: "https://alobooking.vn/san/nha-thi-dau-phu-nhuan-99"
  },
  {
    id: "C068",
    name: "Sân cầu lông Quang Vinh",
    address: "148 Nguyễn Hữu Thọ, TP. Thủ Đức",
    district: "TP. Thủ Đức",
    price: 60000,
    distance: 9.4,
    rating: 3.6,
    quality: 6.0,
    facilities: 2,
    facilityList: ["Gửi xe", "Căng tin"],
    openFrom: 6,
    openTo: 24,
    availability: 0.88,
    url: "https://alobooking.vn/san/san-cau-long-quang-vinh-53"
  },
  {
    id: "C069",
    name: "CLB cầu lông Thành Đạt",
    address: "155 Quang Trung, Quận 10",
    district: "Quận 10",
    price: 110000,
    distance: 5.6,
    rating: 4.4,
    quality: 8.9,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 5,
    openTo: 21,
    availability: 0.93,
    url: "https://alobooking.vn/san/clb-cau-long-thanh-dat-54"
  },
  {
    id: "C070",
    name: "Sân cầu lông Phương Đông",
    address: "87 Trường Chinh, Quận 7",
    district: "Quận 7",
    price: 115000,
    distance: 12.4,
    rating: 4.3,
    quality: 8.7,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 5,
    openTo: 23,
    availability: 0.52,
    url: "https://alobooking.vn/san/san-cau-long-phuong-dong-55"
  },
  {
    id: "C071",
    name: "CLB cầu lông Phúc Long",
    address: "110 Nguyễn Oanh, Quận 1",
    district: "Quận 1",
    price: 50000,
    distance: 11.0,
    rating: 3.6,
    quality: 5.9,
    facilities: 2,
    facilityList: ["Gửi xe", "Căng tin"],
    openFrom: 6,
    openTo: 22,
    availability: 0.88,
    url: "https://alobooking.vn/san/clb-cau-long-phuc-long-56"
  },
  {
    id: "C072",
    name: "CLB cầu lông Hồng Hà",
    address: "31 Nguyễn Hữu Thọ, Quận 7",
    district: "Quận 7",
    price: 50000,
    distance: 6.6,
    rating: 3.5,
    quality: 5.6,
    facilities: 2,
    facilityList: ["Gửi xe", "Căng tin"],
    openFrom: 6,
    openTo: 22,
    availability: 0.51,
    url: "https://alobooking.vn/san/clb-cau-long-hong-ha-57"
  },
  {
    id: "C073",
    name: "Nhà thi đấu Bảo Sơn",
    address: "140 Quang Trung, Quận 12",
    district: "Quận 12",
    price: 75000,
    distance: 13.4,
    rating: 3.9,
    quality: 6.3,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 5,
    openTo: 23,
    availability: 0.76,
    url: "https://alobooking.vn/san/nha-thi-dau-bao-son-58"
  },
  {
    id: "C074",
    name: "Sân cầu lông Ngọc Bích",
    address: "51 Điện Biên Phủ, Quận 3",
    district: "Quận 3",
    price: 75000,
    distance: 8.5,
    rating: 3.9,
    quality: 7.0,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 6,
    openTo: 21,
    availability: 0.62,
    url: "https://alobooking.vn/san/san-cau-long-ngoc-bich-59"
  },
  {
    id: "C075",
    name: "CLB cầu lông Hòa Phú",
    address: "133 Lũy Bán Bích, Phú Nhuận",
    district: "Phú Nhuận",
    price: 80000,
    distance: 5.1,
    rating: 3.9,
    quality: 6.7,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 5,
    openTo: 24,
    availability: 0.75,
    url: "https://alobooking.vn/san/clb-cau-long-hoa-phu-60"
  },
  {
    id: "C076",
    name: "Nhà thi đấu Thành Phát",
    address: "145 Lê Văn Việt, Quận 10",
    district: "Quận 10",
    price: 50000,
    distance: 11.3,
    rating: 3.9,
    quality: 6.1,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 6,
    openTo: 24,
    availability: 0.53,
    url: "https://alobooking.vn/san/nha-thi-dau-thanh-phat-61"
  },
  {
    id: "C077",
    name: "Sân cầu lông Sài Gòn Xanh",
    address: "156 Cách Mạng Tháng 8, Quận 3",
    district: "Quận 3",
    price: 95000,
    distance: 11.0,
    rating: 3.9,
    quality: 7.4,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh"],
    openFrom: 5,
    openTo: 21,
    availability: 0.73,
    url: "https://alobooking.vn/san/san-cau-long-sai-gon-xanh-62"
  },
  {
    id: "C078",
    name: "CLB cầu lông Đông Hưng",
    address: "120 Âu Cơ, Quận 7",
    district: "Quận 7",
    price: 130000,
    distance: 5.3,
    rating: 4.7,
    quality: 9.8,
    facilities: 6,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi", "Cho thuê vợt"],
    openFrom: 6,
    openTo: 23,
    availability: 0.51,
    url: "https://alobooking.vn/san/clb-cau-long-dong-hung-63"
  },
  {
    id: "C079",
    name: "Sân cầu lông Đại Nam",
    address: "137 Lũy Bán Bích, Quận 3",
    district: "Quận 3",
    price: 110000,
    distance: 6.8,
    rating: 4.4,
    quality: 8.4,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 5,
    openTo: 24,
    availability: 0.81,
    url: "https://alobooking.vn/san/san-cau-long-dai-nam-64"
  },
  {
    id: "C080",
    name: "CLB cầu lông Trường Sơn",
    address: "146 Điện Biên Phủ, Tân Phú",
    district: "Tân Phú",
    price: 125000,
    distance: 8.0,
    rating: 4.4,
    quality: 9.2,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 6,
    openTo: 21,
    availability: 0.58,
    url: "https://alobooking.vn/san/clb-cau-long-truong-son-65"
  },
  {
    id: "C081",
    name: "Nhà thi đấu Đông Hưng",
    address: "47 Trường Chinh, Quận 3",
    district: "Quận 3",
    price: 120000,
    distance: 10.4,
    rating: 4.6,
    quality: 8.7,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 5,
    openTo: 22,
    availability: 0.62,
    url: "https://alobooking.vn/san/nha-thi-dau-dong-hung-66"
  },
  {
    id: "C082",
    name: "Sân cầu lông Bình An",
    address: "9 Âu Cơ, Quận 7",
    district: "Quận 7",
    price: 90000,
    distance: 3.8,
    rating: 4.0,
    quality: 7.0,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 6,
    openTo: 22,
    availability: 0.82,
    url: "https://alobooking.vn/san/san-cau-long-binh-an-67"
  },
  {
    id: "C083",
    name: "Nhà thi đấu Đại Nam",
    address: "105 Cách Mạng Tháng 8, Bình Tân",
    district: "Bình Tân",
    price: 95000,
    distance: 11.8,
    rating: 4.3,
    quality: 7.8,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh"],
    openFrom: 6,
    openTo: 23,
    availability: 0.91,
    url: "https://alobooking.vn/san/nha-thi-dau-dai-nam-68"
  },
  {
    id: "C084",
    name: "CLB cầu lông Quang Vinh",
    address: "89 Nguyễn Hữu Thọ, Quận 10",
    district: "Quận 10",
    price: 95000,
    distance: 8.0,
    rating: 4.2,
    quality: 7.3,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh"],
    openFrom: 5,
    openTo: 21,
    availability: 0.91,
    url: "https://alobooking.vn/san/clb-cau-long-quang-vinh-69"
  },
  {
    id: "C085",
    name: "CLB cầu lông Việt Thắng",
    address: "139 Nguyễn Oanh, Quận 12",
    district: "Quận 12",
    price: 50000,
    distance: 6.9,
    rating: 3.6,
    quality: 5.9,
    facilities: 2,
    facilityList: ["Gửi xe", "Căng tin"],
    openFrom: 6,
    openTo: 24,
    availability: 0.88,
    url: "https://alobooking.vn/san/clb-cau-long-viet-thang-70"
  },
  {
    id: "C086",
    name: "CLB cầu lông Thành Phát",
    address: "13 Điện Biên Phủ, Quận 12",
    district: "Quận 12",
    price: 130000,
    distance: 8.4,
    rating: 4.6,
    quality: 9.9,
    facilities: 6,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi", "Cho thuê vợt"],
    openFrom: 6,
    openTo: 22,
    availability: 0.69,
    url: "https://alobooking.vn/san/clb-cau-long-thanh-phat-71"
  },
  {
    id: "C087",
    name: "CLB cầu lông Tân Việt",
    address: "163 Điện Biên Phủ, Quận 7",
    district: "Quận 7",
    price: 75000,
    distance: 5.2,
    rating: 4.1,
    quality: 7.2,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh"],
    openFrom: 6,
    openTo: 21,
    availability: 0.51,
    url: "https://alobooking.vn/san/clb-cau-long-tan-viet-72"
  },
  {
    id: "C088",
    name: "Sân cầu lông Hòa Phú",
    address: "194 Cộng Hòa, Quận 1",
    district: "Quận 1",
    price: 60000,
    distance: 4.1,
    rating: 3.6,
    quality: 5.7,
    facilities: 2,
    facilityList: ["Gửi xe", "Căng tin"],
    openFrom: 5,
    openTo: 22,
    availability: 0.82,
    url: "https://alobooking.vn/san/san-cau-long-hoa-phu-73"
  },
  {
    id: "C089",
    name: "CLB cầu lông Phú Gia",
    address: "196 Cách Mạng Tháng 8, Bình Tân",
    district: "Bình Tân",
    price: 135000,
    distance: 2.0,
    rating: 4.7,
    quality: 9.9,
    facilities: 6,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi", "Cho thuê vợt"],
    openFrom: 6,
    openTo: 22,
    availability: 0.91,
    url: "https://alobooking.vn/san/clb-cau-long-phu-gia-74"
  },
  {
    id: "C090",
    name: "CLB cầu lông Sài Gòn Xanh",
    address: "199 Cách Mạng Tháng 8, Quận 7",
    district: "Quận 7",
    price: 70000,
    distance: 10.8,
    rating: 4.1,
    quality: 7.0,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 6,
    openTo: 24,
    availability: 0.61,
    url: "https://alobooking.vn/san/clb-cau-long-sai-gon-xanh-51"
  },
  {
    id: "C091",
    name: "CLB cầu lông Sơn Trà",
    address: "85 Phạm Văn Đồng, Quận 7",
    district: "Quận 7",
    price: 65000,
    distance: 12.2,
    rating: 3.7,
    quality: 6.2,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 5,
    openTo: 21,
    availability: 0.95,
    url: "https://alobooking.vn/san/clb-cau-long-son-tra-52"
  },
  {
    id: "C092",
    name: "CLB cầu lông Phúc Long",
    address: "110 Nguyễn Oanh, Quận 1",
    district: "Quận 1",
    price: 50000,
    distance: 11.0,
    rating: 3.6,
    quality: 5.9,
    facilities: 2,
    facilityList: ["Gửi xe", "Căng tin"],
    openFrom: 6,
    openTo: 22,
    availability: 0.88,
    url: "https://alobooking.vn/san/clb-cau-long-phuc-long-56"
  },
  {
    id: "C093",
    name: "CLB cầu lông Hồng Hà",
    address: "31 Nguyễn Hữu Thọ, Quận 7",
    district: "Quận 7",
    price: 50000,
    distance: 6.6,
    rating: 3.5,
    quality: 5.6,
    facilities: 2,
    facilityList: ["Gửi xe", "Căng tin"],
    openFrom: 6,
    openTo: 22,
    availability: 0.51,
    url: "https://alobooking.vn/san/clb-cau-long-hong-ha-57"
  },
  {
    id: "C094",
    name: "CLB cầu lông Đông Hưng",
    address: "120 Âu Cơ, Quận 7",
    district: "Quận 7",
    price: 130000,
    distance: 5.3,
    rating: 4.7,
    quality: 9.8,
    facilities: 6,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi", "Cho thuê vợt"],
    openFrom: 6,
    openTo: 23,
    availability: 0.51,
    url: "https://alobooking.vn/san/clb-cau-long-dong-hung-63"
  },
  {
    id: "C095",
    name: "Sân cầu lông Đại Nam",
    address: "137 Lũy Bán Bích, Quận 3",
    district: "Quận 3",
    price: 110000,
    distance: 6.8,
    rating: 4.4,
    quality: 8.4,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 5,
    openTo: 24,
    availability: 0.81,
    url: "https://alobooking.vn/san/san-cau-long-dai-nam-64"
  },
  {
    id: "C096",
    name: "CLB cầu lông Trường Sơn",
    address: "146 Điện Biên Phủ, Tân Phú",
    district: "Tân Phú",
    price: 125000,
    distance: 8.0,
    rating: 4.4,
    quality: 9.2,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 6,
    openTo: 21,
    availability: 0.58,
    url: "https://alobooking.vn/san/clb-cau-long-truong-son-65"
  },
  {
    id: "C097",
    name: "Nhà thi đấu Đông Hưng",
    address: "47 Trường Chinh, Quận 3",
    district: "Quận 3",
    price: 120000,
    distance: 10.4,
    rating: 4.6,
    quality: 8.7,
    facilities: 5,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh", "WiFi"],
    openFrom: 5,
    openTo: 22,
    availability: 0.62,
    url: "https://alobooking.vn/san/nha-thi-dau-dong-hung-66"
  },
  {
    id: "C098",
    name: "Sân cầu lông Bình An",
    address: "9 Âu Cơ, Quận 7",
    district: "Quận 7",
    price: 90000,
    distance: 3.8,
    rating: 4.0,
    quality: 7.0,
    facilities: 3,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ"],
    openFrom: 6,
    openTo: 22,
    availability: 0.82,
    url: "https://alobooking.vn/san/san-cau-long-binh-an-67"
  },
  {
    id: "C099",
    name: "Nhà thi đấu Đại Nam",
    address: "105 Cách Mạng Tháng 8, Bình Tân",
    district: "Bình Tân",
    price: 95000,
    distance: 11.8,
    rating: 4.3,
    quality: 7.8,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh"],
    openFrom: 6,
    openTo: 23,
    availability: 0.91,
    url: "https://alobooking.vn/san/nha-thi-dau-dai-nam-68"
  },
  {
    id: "C100",
    name: "CLB cầu lông Quang Vinh",
    address: "89 Nguyễn Hữu Thọ, Quận 10",
    district: "Quận 10",
    price: 95000,
    distance: 8.0,
    rating: 4.2,
    quality: 7.3,
    facilities: 4,
    facilityList: ["Gửi xe", "Căng tin", "Phòng thay đồ", "Máy lạnh"],
    openFrom: 5,
    openTo: 21,
    availability: 0.91,
    url: "https://alobooking.vn/san/clb-cau-long-quang-vinh-69"
  }
];

// =====================================================================
// Định nghĩa tiêu chí cho AHP + TOPSIS
// =====================================================================
const CRITERIA = [
  { key: "price", label: "Giá thuê", type: "cost", unit: "đ/giờ" },
  { key: "distance", label: "Khoảng cách", type: "cost", unit: "km" },
  { key: "rating", label: "Đánh giá", type: "benefit", unit: "/5" },
  { key: "quality", label: "Chất lượng", type: "benefit", unit: "/10" },
  { key: "facilities", label: "Tiện ích", type: "benefit", unit: "tiện ích" },
  { key: "availability", label: "Khả năng đáp ứng", type: "benefit", unit: "%" }
];

// Trọng số mặc định (tham khảo từ tài liệu, có thể điều chỉnh)
const DEFAULT_WEIGHTS = {
  price: 20,
  distance: 20,
  rating: 25,
  quality: 25,
  facilities: 10
};